# Dependabot will run on day 19 of each month at 02:23 (Europe/Berlin timezone)
version: 2
updates:

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'cron'
      cronjob: '17 4 6 * *'
      timezone: 'Europe/Berlin'
    open-pull-requests-limit: 15
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: 'typescript'
        update-types:
          - 'version-update:semver-major'
      - dependency-name: '@types/node'
        update-types:
          - 'version-update:semver-major'
      - dependency-name: 'eslint'
        update-types:
          - 'version-update:semver-major'
      - dependency-name: '@iobroker/eslint-config'
        update-types:
          - 'version-update:semver-major'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'cron'
      cronjob: '43 5 13 * *'
      timezone: 'Europe/Berlin'
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: '*'
        update-types:
          - 'version-update:semver-major'
    open-pull-requests-limit: 15
